project_id = "ahlikyhgcqvrdvbtkghh"

[functions.generate-script]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false

[functions.script-assistant]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.extract-characters]
verify_jwt = false
